### ISSUE TITLE
🧑‍🦱Day 1 - Time with Immanuel & the onboarding checklist

### ISSUE THREAD

**Issue by renevanosnabrugge** [XpiritBV/employee-HiddedeSmet#1]
## Topics to discuss

[Azure DevOps page](https://dev.azure.com/xpirit/Xpirit%20TOM/_wiki/wikis/Xpirit-TOM.wiki?friendlyName=People&pagePath=/Xpirit%20TOM/People/Onboarding%20checklist)

[XKE calendar / XMS Tuesdays](https://xke.xebia.com/)

Buddy system

Writing hours

## Onboarding Checklist

- [ ] 💻Did you receive your gear (laptop, accessories, telephone, sim card)? 
- [ ] 🚗 Car and tankcard (if applicable)?
- [ ] 🔑  Do you have access to the Xebia HQ (your tag)?
- [ ] 📆 Check out the XKE calendar via xke.xebia.com
- [ ] 🔗 Connect your MPN and GitHub account to XMS
- [ ] 🍽️ Have dinner with your lover or a friend to celebrate your start. A present from us! Expense the costs via X3.
- [ ]  👕 (Not possible right now) Order your XMS swag: swag.xebia.com! You can login with your Xebia e-mail credentials.

Any questions bout ordering swag, the XKE calendar or something else? Feel free to reach out to Natascha!
