### ISSUE TITLE
✨ Day 4 - Personal Branding

### ISSUE THREAD

**Issue by renevanosnabrugge** [XpiritBV/employee-HiddedeSmet#12]
# Personal branding
At Xebia, we live by our authority mission. Today will be all about "personal branding". Where can you start, or continue, building your personal brand and what support and tools can you use within Xebia?

## Your schedule for today
09:00 - 11:30 ✍️ Writing a blog by Rob
11:30 - 12:00 🥪 Lunch  
12:00 - 13:00 ✨ Personal Branding by Kim 
13:00 - 17:00 ⏳ Time to get started

## Extra info & track your progress
```[tasklist]
### Tasks
- [ ] https://github.com/XpiritBV/XMS-Onboarding/issues/21
- [ ] https://github.com/XpiritBV/XMS-Onboarding/issues/23
- [ ] https://github.com/XpiritBV/XMS-Onboarding/issues/24
```
