### ISSUE TITLE
💼 Day 3 - Become Consultant Ready 

### ISSUE THREAD

**Issue by renevanosnabrugge** [XpiritBV/employee-HiddedeSmet#13]
# 🏁 Ready, set, go!
Whether you've been a consultant with your previous organization or not, we want to make sure that you are prepped and know everything you need and want to know, before starting your first epic assignment. Today is all about absorbing the Xebia way of consulting. 

## Your schedule for today

09:00 - 10:30 🗣️ Consultative selling by **Matthias**  
10:30 - 11:30 🔨 Create / Update your CV - add info see email
11:30 - 12:00 🥪 Lunch 
12:00 - 14:00 💡 XMS Signature & Engineering Culture by @renevanosnabrugge  
14:00 - 17:00 💻 Time to do some work / set up your super powers

## Extra info & track your progress
```[tasklist]
### Tasks
- [ ] https://github.com/XpiritBV/XMS-Onboarding/issues/32
- [ ] https://github.com/XpiritBV/XMS-Onboarding/issues/35
- [ ] https://github.com/XpiritBV/XMS-Onboarding/issues/33
- [ ] https://github.com/XpiritBV/XMS-Onboarding/issues/34
```
